{% set name = "hyperframe" %}
{% set version = "3.2.0" %}
{% set sha256 = "05f0e063e117c16fcdd13c12c93a4424a2c40668abfac3bb419a10f57698204e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - hyperframe

about:
  home: http://python-hyper.org/hyperframe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure-Python HTTP/2 framing '
  dev_url: https://github.com/python-hyper/hyperframe

extra:
  recipe-maintainers:
    - primozgodec
    - astaric
