travis:
  secure:
    BINSTAR_TOKEN: 3YOR9gd/9t3cqQwAFYuaeChr5QfHFsD4V0I7dWs0Pz8HvcL9Hq56LnDiOX/6b0Wouw/n1rnDrMNwuxY5GG1Ec457n7rAV0K0dqlycPgEPDhC3xMq0PITiP1fPeCf1G+A0+VO0Dq/IRVXSY2v+fkvYMw1RsXod4OQp9Dud8aVRqv4dPIxFOBCKW0bE7maA6U/VM7v6fAKo4Mw845upQY+gg9GVUsxpmd8P3hm1IzlQyahRr2oz5zBi+1+mTFOzYmNoLA2OslYVW08ZuzLn4lK8TxbCL5nbPMCZ/VOEI+KOqVyA5sPFLZe1iZxY8NsYWW00FzdByKaCcWX07QRXDykI1QpjHw24V1QXF5y+yUvVBaU7kVMAbjE25RTaszo6EclUkgM77l+vQhi1g5Y8zz6MZwb1wpd34nnKxIzh/PMKf/ffcmEBq1hhCks1grmX4lUzZs3KIM+XmOr9FAwfp0TvcloFWwZn1SulO7Cg2I4NfeISWyVkZU0MutgCeL4DexIDwttcCZIj8Om03QFV2scZ8n0xAK3vakU9qlIbiyccR7QhNCNRUkwFsrnpUCB0vsIFdlvXTeFtXKmWKPSEuvbX2Dj2IV3/yA+6aLX7Z4yOD7zEzq4VRraKNhAzi+5+/s+/kcLDYYjVykutjFQkwtkzhzqEXqJB02tNdtMoI6KvmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
